### ISSUE TITLE
AI 기능 추가

### ISSUE THREAD

**Issue by jabberwocker04** [jabberwocker04/gitandrun#113]
## Description
AI API를 통해 질문을 생성할 경우 createdAt을 생성하여 생성 날짜를 기록하려 합니다.
생성 날짜가 14일이 넘어가면 자동으로 삭제되게 하여 테이블을 관리합니다.

## Todo
- [x] AI Domain CreatedAt 생성
- [x] CreatedAt이 생성날짜로부터 +14일이 되면 DB에서 자동 삭제

## ETC
기타사항

**Comment by soo1e** [comment]
14일 지나면 삭제하는 거 매우 좋은 것 같습니다
